<a href="https://colab.research.google.com/github/priyal6/DL/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
my_tensor = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float32,
                         device="cpu", requires_grad=True) # Changed device to 'cpu'

print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [ ]:
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

torch.float32
cpu
torch.Size([2, 3])
True


In [ ]:
x = torch.empty(size=(3,3))
print(x)
y = torch.zeros((3,3))
print(y)
x = torch.rand((3,3))
print(x)
x = torch.eye(5,5)
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)

x = torch.empty(size=(1,5)).uniform_(0,1)
print(x)
x = torch.diag(torch.ones(3))
print(x)

tensor([[2.7019e-22, 0.0000e+00, 2.7017e-22],
        [0.0000e+00, 6.0979e-38, 6.2815e-38],
        [0.0000e+00, 0.0000e+00, 5.6828e-08]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.4313, 0.1145, 0.6378],
        [0.8338, 0.2974, 0.8021],
        [0.2762, 0.4654, 0.0250]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[0.1510, 0.8778, 0.1203, 0.2636, 0.1739]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [ ]:
tensor = torch.arange(4)
print(tensor.bool())
print(tensor.short())
print(tensor.long())
print(tensor.half())
print(tensor.float())
print(tensor.double())

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [ ]:
import numpy as np
np_array = np.zeros((5,5))
tensor = torch.from_numpy(np_array)
np_array_back = tensor.numpy()
print(tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [ ]:
#tensor math
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])

z1 = torch.empty(3)
torch.add(x,y, out=z1)


tensor([10., 10., 10.])

In [ ]:
z2 = torch.add(x,y)
z2 = x+y
print(z2)

tensor([10, 10, 10])


In [ ]:
z = torch.true_divide(x,y)
t = torch.zeros(3)
t.add_(x) #_ inplace

tensor([1., 2., 3.])

In [ ]:
#exponents
z = x.pow(2)
print(z)

tensor([1, 4, 9])


In [ ]:
#comparsion
z = x>0
print(z)
z= x<0

tensor([True, True, True])


In [ ]:
#matrix multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))
x3 = torch.mm(x1,x2)
x3 = x1.mm(x2)
print(x3)

tensor([[1.7590, 1.7618, 1.1958],
        [1.2474, 1.2976, 1.2838]])


In [ ]:
matrix_exp = torch.rand(5,5)
print(matrix_exp.matrix_power(3))

tensor([[4.2174, 3.3973, 3.3190, 4.4606, 2.5381],
        [1.7319, 1.4816, 1.4166, 2.0815, 1.2123],
        [4.3339, 3.7531, 3.4440, 5.0550, 3.1353],
        [2.9338, 2.2975, 2.2200, 3.0593, 1.6969],
        [3.1193, 2.7704, 2.4347, 3.7970, 2.4202]])


In [ ]:
#element wise mult
z = x*y
print(z)

tensor([ 9, 16, 21])


In [ ]:
#dot product
z = torch.dot(x,y)
print(z)

tensor(46)


In [ ]:
#batch matrix
batch = 32
n = 10
m= 20
p =30
tensor1 = torch.rand((batch, n,m))
print(tensor1)
tensor1.shape

tensor([[[0.3053, 0.7513, 0.3390,  ..., 0.2822, 0.6467, 0.1075],
         [0.5459, 0.3259, 0.8191,  ..., 0.8491, 0.5911, 0.9775],
         [0.4173, 0.9081, 0.5664,  ..., 0.1456, 0.8726, 0.0268],
         ...,
         [0.3678, 0.2417, 0.5799,  ..., 0.5641, 0.8837, 0.9641],
         [0.6225, 0.8889, 0.7058,  ..., 0.9873, 0.0255, 0.1799],
         [0.5414, 0.1583, 0.0777,  ..., 0.1667, 0.3096, 0.9409]],

        [[0.7458, 0.0049, 0.1359,  ..., 0.0523, 0.3081, 0.0893],
         [0.1674, 0.4249, 0.6123,  ..., 0.0063, 0.8825, 0.5321],
         [0.6989, 0.9273, 0.9034,  ..., 0.0877, 0.4546, 0.7906],
         ...,
         [0.3957, 0.2437, 0.1623,  ..., 0.5828, 0.5757, 0.7465],
         [0.7558, 0.6049, 0.3218,  ..., 0.3988, 0.2560, 0.8718],
         [0.9138, 0.6778, 0.3273,  ..., 0.6603, 0.3315, 0.4468]],

        [[0.4302, 0.5586, 0.3832,  ..., 0.9274, 0.6946, 0.8821],
         [0.0489, 0.3844, 0.6990,  ..., 0.4196, 0.0341, 0.2930],
         [0.8009, 0.7729, 0.1207,  ..., 0.4171, 0.3963, 0.

torch.Size([32, 10, 20])

In [ ]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z = x1-x2

In [ ]:
#other operations
sum_x = torch.sum(x,dim=0)
##print(sum_x)
x = torch.randn((1,3))
##print(x)

values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
print(values, indices)

tensor([-0.6318, -0.7589,  0.6316]) tensor([0, 0, 0])


In [ ]:
z = torch.argmax(x)
#z = torch.argmin(x)
print(z)

tensor(2)


In [ ]:
x = torch.tensor([1,2,3])
z = torch.eq(x,y)
print(z)

tensor([False, False, False])


In [ ]:
torch.sort(y, dim=0, descending=False)

torch.return_types.sort(
values=tensor([7, 8, 9]),
indices=tensor([2, 1, 0]))

In [ ]:
z = torch.clamp(x, min=0, max=10)
print(z)

tensor([1, 2, 3])


In [ ]:
x = torch.tensor([1,0,1,1,1], dtype=bool)
z = torch.any(x)
z = torch.all(x)
print(z)

tensor(False)


In [ ]:
#tensor indexing
batch_size = 10
features = 25
x = torch.rand((batch_size, features))
print(x[0].shape)

print(x[:,0].shape)

print(x.shape)
print(x[2,0:10])

torch.Size([25])
torch.Size([10])
torch.Size([10, 25])
tensor([0.6161, 0.0660, 0.3587, 0.7242, 0.2119, 0.1921, 0.4333, 0.7556, 0.1030,
        0.4117])


In [ ]:
#fancy index
x = torch.arange(10)
indices = [2,5,8]
print(x[indices])

tensor([2, 5, 8])


In [ ]:
x = torch.rand((3,5))
row = torch.tensor([1,0])
cols = torch.tensor([1,0])
print(x[row, cols].shape)

torch.Size([2])


In [ ]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) | (x > 8)])
print(x[x.remainder(2)==0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [ ]:
print(torch.where(x>5, x, x*2))
x = torch.tensor([0, 0, 1, 2, 2, 3, 4]).unique()
print(x)
print(x.ndimension())
print(x.numel())

tensor([0, 2, 4, 6, 8])
tensor([0, 1, 2, 3, 4])
1
5


In [ ]:
#reshaping
x = torch.arange(9)

x_3x3 = x.view(3,3)
print(x_3x3.shape)
x_3x3 = x.reshape(3,3)

y = x_3x3.t()
print(y.reshape(9))

torch.Size([3, 3])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [ ]:
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))
print(torch.cat((x1,x2), dim=0).shape)
print(torch.cat((x1,x2), dim=1).shape)

torch.Size([4, 5])
torch.Size([2, 10])


In [ ]:
z = x1.view(-1)
print(z.shape)


batch = 64
x = torch.rand((batch,2,5))
z = x.view(batch, -1)
print(z.shape)

torch.Size([10])
torch.Size([64, 10])


In [ ]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)

torch.Size([1, 10])


In [ ]:
import torch
from torchvision import datasets, transforms

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,),(0.3081,))
])

trainset = datasets.MNIST(root='./data', train=True, download=True, transform = transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64,shuffle=True)


testset = datasets.MNIST(root='./data', train=False, download=True,transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64,shuffle=False )

100%|██████████| 9.91M/9.91M [00:00<00:00, 38.3MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 1.08MB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 8.24MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 3.29MB/s]


In [ ]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class SimpleMNISTModel(nn.Module):
  def __init__(self):
    super(SimpleMNISTModel,self).__init__()
    self.fc1 = nn.Linear(28*28, 128)
    self.fc2 = nn.Linear(128,10)

  def forward(self,x):
    x = x.view(-1,28*28)
    x = F.relu(self.fc1(x))
    x = self.fc2(x)
    return x


model = SimpleMNISTModel()
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.01)


#training loop
epochs = 5
for epoch in range(epochs):
  model.train()
  running_loss = 0.0

  for images, labels in trainloader:
    optimizer.zero_grad()
    outputs = model(images)
    loss = criterion(outputs, labels)
    loss.backward()
    optimizer.step()
    running_loss += loss.item()

    print(f"Epoch {epoch+1} - Loss: {running_loss/len(trainloader):.4f}")

model.eval()
correct = 0
total = 0

with torch.no_grad():
  for images, labels in testloader:
    outputs = model(images)
    _, predicted = torch.max(outputs.data, 1)
    total = total + labels.size(0)
    correct = correct + (predicted == labels).sum().item()

print(f"Accuracy on test set: {100 * correct / total:.2f}%")

Epoch 1 - Loss: 0.0026
Epoch 1 - Loss: 0.0051
Epoch 1 - Loss: 0.0076
Epoch 1 - Loss: 0.0101
Epoch 1 - Loss: 0.0125
Epoch 1 - Loss: 0.0149
Epoch 1 - Loss: 0.0173
Epoch 1 - Loss: 0.0197
Epoch 1 - Loss: 0.0221
Epoch 1 - Loss: 0.0245
Epoch 1 - Loss: 0.0268
Epoch 1 - Loss: 0.0291
Epoch 1 - Loss: 0.0314
Epoch 1 - Loss: 0.0337
Epoch 1 - Loss: 0.0359
Epoch 1 - Loss: 0.0381
Epoch 1 - Loss: 0.0404
Epoch 1 - Loss: 0.0426
Epoch 1 - Loss: 0.0448
Epoch 1 - Loss: 0.0471
Epoch 1 - Loss: 0.0492
Epoch 1 - Loss: 0.0514
Epoch 1 - Loss: 0.0535
Epoch 1 - Loss: 0.0556
Epoch 1 - Loss: 0.0577
Epoch 1 - Loss: 0.0599
Epoch 1 - Loss: 0.0620
Epoch 1 - Loss: 0.0641
Epoch 1 - Loss: 0.0661
Epoch 1 - Loss: 0.0681
Epoch 1 - Loss: 0.0701
Epoch 1 - Loss: 0.0721
Epoch 1 - Loss: 0.0741
Epoch 1 - Loss: 0.0761
Epoch 1 - Loss: 0.0781
Epoch 1 - Loss: 0.0800
Epoch 1 - Loss: 0.0819
Epoch 1 - Loss: 0.0838
Epoch 1 - Loss: 0.0858
Epoch 1 - Loss: 0.0877
Epoch 1 - Loss: 0.0896
Epoch 1 - Loss: 0.0914
Epoch 1 - Loss: 0.0931
Epoch 1 - L