<a href="https://colab.research.google.com/github/priyal6/DL/blob/main/Tensorflow_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
#initialiazation of tensors
x = tf.constant(4, shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [ ]:
x = tf.constant ([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x = tf.ones((3,3))
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.zeros((2,3))

In [ ]:
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [ ]:
x = tf.eye(3)
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.random.normal((3,3), mean = 0, stddev=1)

In [ ]:
print(x)

tf.Tensor(
[[ 0.597438    0.6302906   0.7005907 ]
 [-0.21395762  0.01701938  0.73265904]
 [-0.00589438 -1.9100707   1.1444747 ]], shape=(3, 3), dtype=float32)


In [ ]:
x = tf.random.uniform((1,3), minval = 0, maxval = 1)

In [ ]:
print (x)

tf.Tensor([[0.5723951  0.48942482 0.5200814 ]], shape=(1, 3), dtype=float32)


In [ ]:
x = tf.range(9)
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [ ]:
x = tf.range(start =1 , limit = 10, delta = 2)
print(x)

tf.Tensor([1 3 5 7 9], shape=(5,), dtype=int32)


In [ ]:
x = tf.cast(x, dtype= tf.float64)
print(x)

tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [ ]:
#Mathematical Operations

In [ ]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [ ]:
z = tf.add(x,y)

In [ ]:
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
z= x+y
print(z)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [ ]:
z = tf.subtract(x,y)
z = x-y

In [ ]:
z = tf.divide(x,y)
z = x/y

In [ ]:
z = tf.multiply(x,y)
z = x * y

In [ ]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [ ]:
z = tf.tensordot(x, y , axes = 1)
print(z)

tf.Tensor(46, shape=(), dtype=int32)


In [ ]:
z = tf.reduce_sum(x*y,axis = 0)

In [ ]:
z = x**5
print(z)

tf.Tensor([  1  32 243], shape=(3,), dtype=int32)


In [ ]:
x = tf.random.normal((2,3))
y = tf.random.normal((3,4))
z = tf.matmul(x,y)
print(z)

tf.Tensor(
[[-0.91227764 -1.3990407   0.39264062 -0.24703556]
 [ 2.0282838   1.3211185   2.4863527   4.04435   ]], shape=(2, 4), dtype=float32)


In [ ]:
#Indexing

x = tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)


In [ ]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [ ]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [ ]:
indices = tf.constant([0,3])
x_ind = tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [ ]:
x = tf.constant([[1,2],[3,4],[5,6]])

In [ ]:
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [ ]:
#Reshaping

In [ ]:
x = tf.range(9)
print(x)
x = tf.reshape(x,(3,3))
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [ ]:
x = tf.transpose(x, perm=[1,0])
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
